data-dir: data_1
rpc-port: 8401
node-name: proglog-1
bind-addr: 127.0.0.1:7374
bootstrap: false
start-join-addrs: ["127.0.0.1:7373"]
# server-tls-cert-file: /Users/admin/.proglog/server.pem
# server-tls-key-file: /Users/admin/.proglog/server-key.pem
# server-tls-ca-file: /Users/admin/.proglog/ca.pem
# peer-tls-cert-file: /Users/admin/.proglog/root-client.pem
# peer-tls-key-file: /Users/admin/.proglog/root-client-key.pem
# peer-tls-ca-file: /Users/admin/.proglog/ca.pem
# acl-model-file: /Users/admin/.proglog/model.conf
# acl-policy-file: /Users/admin/.proglog/policy.csv